/*
--- Data Types
Boolean
○ True or False

Character
○ char, varchar, and text

Numeric
○ integer and floating-point number

Temporal
○ date, time, timestamp, and interval

UUID
○ Universally Unique Identifiers

Array
○ Stores an array of strings, numbers, etc.

JSON
Hstore key-value pair

Special types such as network address and geometric data.

When creating databases and tables, you should carefully consider which data types 
should be used for the data to be stored.

When creating a database and table, take your time to plan for long term storage

Remember you can always remove historical information you've decided you aren't using, 
but you can't go back in time to add in information!
*/



/*
--- Primary & Foreign Keys
A primary key is a column or a group of columns used to identify a row uniquely in a table.

For example, in our dvdrental database we saw customers had a unique, non-null customer_id 
column as their primary key.

A foreign key is a field or group of fields in a table that uniquely identifies a row in another table.

A foreign key is defined in a table that references to the primary key of the other table.

The table that contains the foreign key is called referencing table or child table.

The table to which the foreign key references is called referenced table or parent table.

A table can have multiple foreign keys depending on its relationships with other tables.
*/



/*
--- Constraints
Constraints are the rules enforced on data columns on table.

These are used to prevent invalid data from being entered into the database.

This ensures the accuracy and reliability of the data in the database.

Constraints can be divided into two main categories:
--Column Constraints
* Constrains the data in a column to adhere to certain conditions.

--Table Constraints
* Applied to the entire table rather than to an individual column.


The most common COLUMN constraints used:
--NOT NULL Constraint
* Ensures that a column cannot have NULL value.

--UNIQUE Constraint
* Ensures that all values in a column are different.

--PRIMARY Key
* Uniquely identifies each row/record in a database table.

--FOREIGN Key
* Constrains data based on columns in other tables.

--CHECK Constraint
* Ensures that all values in a column satisfy certain conditions.

--EXCLUSION Constraint
* Ensures that if any two rows are compared on the specified column or expression using 
the specified operator, not all of these comparisons will return TRUE.


The most common TABLE constraints used:
--CHECK (condition)
* To check a condition when inserting or updating data.

--REFERENCES
* To constrain the value stored in the column that must exist in a column in another table.

--UNIQUE (column_list)
* Forces the values stored in the columns listed inside the parentheses to be unique.

--PRIMARY KEY(column_list)
* Allows you to define the primary key that consists of multiple columns.
*/



/*
-- CREATE Table

CREATE TABLE table_name (
  column_name TYPE column_constraint,
  column_name TYPE column_constraint,
  table_constraint table_constraint
) INHERITS existing_table_name;

-- SERIAL
○ In PostgreSQL, a sequence is a special kind of database object that generates 
a sequence of integers.

○ A sequence is often used as the primary key column in a table.

○ It will create a sequence object and set the next value generated by the sequence 
as the default value for the column.

○ This is perfect for a primary key, because it logs unique integer entries for you 
automatically upon insertion.

If a row is later removed, the column with the SERIAL data type will not adjust, 
marking the fact that a row was removed from the sequence, for example

1,2,3,5,6,7

You know row 4 was removed at some point
*/
--- Example
CREATE TABLE players(
  player_id SERIAL PRIMARY KEY,
  age SMALLINT column_constraint
)

--- CREATE TABLE: pgAdmin practice
CREATE TABLE account(
	user_id SERIAL PRIMARY KEY,
	username VARCHAR(50) UNIQUE NOT NULL,
	password VARCHAR(50) NOT NULL,
	email VARCHAR(250) UNIQUE NOT NULL,
	created_on TIMESTAMP NOT NULL,
	last_login TIMESTAMP
)

CREATE TABLE job(
	job_id SERIAL PRIMARY KEY,
	job_name VARCHAR(200) UNIQUE NOT NULL,
)

